#!/bin/bash
# ============================================================================
# MCFGC Club Manager -- Production Setup Script
#
# Run this once on a fresh deployment to generate .env.production with
# auto-generated secrets. Third-party API keys (Stripe, Resend, Gmail)
# must be filled in manually.
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#
# Then edit .env.production to add your API keys and admin credentials.
# Finally:
#   docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build
# ============================================================================

set -e

ENV_FILE=".env.production"

# Don't overwrite an existing .env.production
if [ -f "$ENV_FILE" ]; then
  echo "========================================="
  echo " $ENV_FILE already exists."
  echo " Delete it first if you want to regenerate."
  echo "========================================="
  exit 1
fi

echo "========================================="
echo " MCFGC Club Manager -- Production Setup"
echo "========================================="
echo ""

# Prompt for required values
read -p "Enter your domain (e.g. club.mcfgcinc.com): " APP_DOMAIN
if [ -z "$APP_DOMAIN" ]; then
  echo "Error: Domain is required."
  exit 1
fi

read -p "Enter admin email: " ADMIN_EMAIL
if [ -z "$ADMIN_EMAIL" ]; then
  echo "Error: Admin email is required."
  exit 1
fi

read -p "Enter admin full name [Club Administrator]: " ADMIN_NAME
ADMIN_NAME=${ADMIN_NAME:-"Club Administrator"}

read -sp "Enter admin password (min 8 chars): " ADMIN_PASSWORD
echo ""
if [ ${#ADMIN_PASSWORD} -lt 8 ]; then
  echo "Error: Password must be at least 8 characters."
  exit 1
fi

# Auto-generate secrets
echo ""
echo "Generating secrets..."

BETTER_AUTH_SECRET=$(openssl rand -base64 32)
ENCRYPTION_KEY=$(openssl rand -hex 32)
DB_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)
CRON_SECRET=$(openssl rand -hex 32)

echo "  BETTER_AUTH_SECRET: generated"
echo "  ENCRYPTION_KEY:     generated (64-char hex)"
echo "  DB_PASSWORD:        generated"
echo "  CRON_SECRET:        generated"

# Write .env.production
cat > "$ENV_FILE" << ENVEOF
# MCFGC Club Manager -- Production Environment
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# -- Domain
APP_DOMAIN=${APP_DOMAIN}

# -- Derived URLs (auto-set from APP_DOMAIN)
BETTER_AUTH_URL=https://${APP_DOMAIN}
NEXT_PUBLIC_BETTER_AUTH_URL=https://${APP_DOMAIN}

# -- Database
DB_USER=mcfgc
DB_PASSWORD=${DB_PASSWORD}
DB_NAME=mcfgc

# -- Security Secrets (auto-generated)
BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# -- Admin Seed (used on first startup only)
ADMIN_EMAIL=${ADMIN_EMAIL}
ADMIN_PASSWORD=${ADMIN_PASSWORD}
ADMIN_NAME=${ADMIN_NAME}

# -- Stripe (required)
STRIPE_SECRET_KEY=
STRIPE_PUBLISHABLE_KEY=
STRIPE_WEBHOOK_SECRET=

# -- Resend (optional)
RESEND_API_KEY=

# -- Gmail SMTP (optional)
GMAIL_USER=
GMAIL_APP_PASSWORD=

# -- Cron (scheduled jobs)
CRON_SECRET=${CRON_SECRET}

# -- Google Drive Backup (optional -- daily automated backups)
GOOGLE_SERVICE_ACCOUNT_KEY=
GOOGLE_DRIVE_FOLDER_ID=

# -- App Port
APP_PORT=3001
ENVEOF

echo ""
echo "========================================="
echo " .env.production created!"
echo "========================================="
echo ""
echo " Next steps:"
echo "  1. Edit $ENV_FILE and add your Stripe API keys"
echo "  2. Optionally add Resend and/or Gmail credentials"
echo "  3. Point your Cloudflare Tunnel to http://localhost:${APP_PORT:-3001}"
echo "  4. Start the app:"
echo ""
echo "     docker compose -f docker-compose.prod.yml --env-file .env.production up -d --build"
echo ""
echo "  5. Set up host crontab for scheduled jobs:"
echo "     crontab -e"
echo "     # Lapse check: Feb 1 at 5:00 UTC"
echo "     0 5 1 2 * curl -sf -X POST -H \"x-cron-secret: \${CRON_SECRET}\" http://localhost:3001/api/cron/lapse-check"
echo "     # Scheduled broadcasts: Every 5 minutes"
echo "     */5 * * * * curl -sf -X POST -H \"x-cron-secret: \${CRON_SECRET}\" http://localhost:3001/api/cron/send-scheduled"
echo "     # DB backup: Daily at 7:00 UTC"
echo "     0 7 * * * curl -sf -X POST -H \"x-cron-secret: \${CRON_SECRET}\" http://localhost:3001/api/cron/db-backup"
echo ""
echo "  6. Visit https://${APP_DOMAIN} and log in with:"
echo "     Email:    ${ADMIN_EMAIL}"
echo "     Password: (the password you just entered)"
echo ""
